### PR TITLE
Add bun to bundlers.json

### PR DESCRIPTION
**Pull request by torifat**
Thank you for contributing to the Node.js Toolbox catalog! 🙏

Note: Node.js Toolbox is specifically for backend libraries. If a library works both in the browser AND in Node.js feel free to add it. Libraries that work ONLY in the browser are out of scope for now.

**Before submitting your pull request, please make sure:**

- [x] To use the _exact_ package name as it appears on NPM (and `npm install <package-name>`)
- [x] The packages are listed in alphabetical order
- [x] The package doesn't already exist in a different category
- [x] Description doesn't have a dot (.) at the end
- [x] To format with Prettier before committing (`npm run prettier`)

### CODE REVIEW

**Comment by Maximization** [comment]
@torifat Thanks for your contribution! Even though Bun also does bundling, it doesn't seem right to put it in the same category as Esbuild and Webpack. It's more comparable with Deno, a JavaScript runtime (and Node.js alternative). What do you think?

**Comment by torifat** [comment]
It does a bunch of different things and falls into multiple categories. Not sure if it's possible to add a single package to multiple categories.

**Comment by Maximization** [comment]
Do you think it's common for folks to add Bun as a dependency to their Node.js project and use it as a bundler? Or are folks more likely to use it to replace Node.js, which then conveniently comes with the bundler feature?

I'm assuming the later, and since Node.js Toolbox targets the Node.js ecosystem (not Deno or Bun), I don't see how a Node.js alternative would fit here. But I might be wrong.

**Comment by torifat** [comment]
> Note: Node.js Toolbox is specifically for backend libraries.

Given your focus is on BE, it makes sense from that point of view. All other use cases are mostly FE centric.

**Comment by Maximization** [comment]
Yeah the focus is on back-end for now :). Thanks for understanding and for the constructive discussion! Feel free to open more issues/PRs in the future ❤️

**Pull request closed without merging**
