### PR TITLE
Add: appwrite @tsed/core

### PR DESCRIPTION
**Pull request by openapphub**
Thank you for contributing to the Node.js Toolbox catalog! 🙏

Note: Node.js Toolbox is specifically for backend libraries. If a library works both in the browser AND in Node.js feel free to add it. Libraries that work ONLY in the browser are out of scope for now.

**Before submitting your pull request, please make sure:**

- [x] To use the _exact_ package name as it appears on NPM (and `npm install <package-name>`)
- [x] The packages are listed in alphabetical order
- [x] The package doesn't already exist in a different category
- [x] Description doesn't have a dot (.) at the end
- [x] To format with Prettier before committing (`npm run prettier`)

### CODE REVIEW

**Comment by Maximization** [comment]
@openapphub Thanks for contributing! Appwrite is more of a Backend-as-a-Service library and doesn't fit very well in the CMS category. There's no BaaS category yet but will add soon https://github.com/Maximization/nodejs-toolbox-catalog/issues/58

Ts.ED looks cool. Thanks for bringing it to my attention

**Comment by Maximization** [comment]
Change is live at https://nodejstoolbox.com/categories/full-stack-frameworks

**Review by Elgayar777 — APPROVED** [review]
- [ ]

**Review by Elgayar777 — COMMENTED** [review]
- [ ]

**Pull request merged**
