### PR TITLE
Added FoalTS framework to fullstack frameworks

### PR DESCRIPTION
**Pull request by maikofelix47**
Thank you for contributing to the Node.js Toolbox catalog! 🙏

Note: Node.js Toolbox is specifically for backend libraries. If a library works both in the browser AND in Node.js feel free to add it. Libraries that work ONLY in the browser are out of scope for now.

**Before submitting your pull request, please make sure:**

- [x] To use the _exact_ package name as it appears on NPM (and `npm install <package-name>`)
- [x] The packages are listed in alphabetical order
- [x] The package doesn't already exist in a different category
- [x] Description doesn't have a dot (.) at the end
- [x] To format with Prettier before committing (`npm run prettier`)

### CODE REVIEW

**Comment by Maximization** [comment]
@maikofelix47 Thanks again for your contribution! ❤️

Change is live: https://nodejstoolbox.com/categories/full-stack-frameworks

**Comment by maikofelix47** [comment]
Thank you @Maximization . I have become a regular user of the tool so i will try and improve it any way i can.

**Comment by Maximization** [comment]
@maikofelix47 Fantastic! Let me know if there's any features/statistics missing that could be added to make it easier to find & compare libraries. I have some ideas in mind but curious to hear your suggestions.

**Comment by maikofelix47** [comment]
@Maximization What i feel would make things better are
1. Search functionality
2. Filter by category
3. Weekly download statistics and graph showing the trend
4. Order libraries by stars or downloads.

**Comment by Maximization** [comment]
@maikofelix47 Thank you this is very valuable 🙏. Could you please elaborate a bit more on no. 1? What would you like to search for and where should you navigate to when clicking on the search result? And for no. 2, how is the category filter different from the category page?

**Comment by maikofelix47** [comment]
@Maximization Thanks. For 1. Sometimes you may know a library but are not sure which category it belongs to. So instead of having to go through all the categories,it would be easier to search for the library name and the displayed results can indicate the library as well as the category it belongs to. On clicking the search result it can take them to the category page just like they clicked on the category since we don't have a library details page.
For item 2, with time the list of categories may grow longer and one may only be interested in 1 or 2 categories. Filter allows one to filter out all the other categories.

**Comment by Maximization** [comment]
Awesome! The first point is very clear and I've added it to the roadmap. For a growing list of categories I had the idea of grouping categories into sections such as Code Quality, Data Persistence, Developer Tools, Testing, etc. That'll make it easier to browse.

I don't fully understand what you mean by filtering out categories, how does the page look like and what's the user interaction? Thanks for taking the time to explain this btw, appreciate it!

**Comment by maikofelix47** [comment]
@Maximization Thanks for responding. The categories page is okay as it is. My suggestion was to cater to future cases where the list grew longer. If you are planning to group them as you've mentioned then it should sort it out.

**Pull request merged**
