### PR TITLE
Added Joi , Yup and Zod to object schema validators category

### PR DESCRIPTION
**Pull request by maikofelix47**
Thank you for contributing to the Node.js Toolbox catalog! 🙏

Note: Node.js Toolbox is specifically for backend libraries. If a library works both in the browser AND in Node.js feel free to add it. Libraries that work ONLY in the browser are out of scope for now.

**Before submitting your pull request, please make sure:**

- [x] To use the _exact_ package name as it appears on NPM (and `npm install <package-name>`)
- [x] The packages are listed in alphabetical order
- [x] The package doesn't already exist in a different category
- [x] Description doesn't have a dot (.) at the end
- [x] To format with Prettier before committing (`npm run prettier`)

### CODE REVIEW

**Comment by Maximization** [comment]
Thanks for your PR @maikofelix47 ! These are great validators, but they're not JSON Schema based (which this category is for). We could add a new category, or change this category to be more broadly about validators and not just JSON Schema. What do you think?

**Comment by maikofelix47** [comment]
@Maximization I agree. We may have to come up with a different subcategory for them to be more specific just like we have HTTP frameworks and full-stack framework categories. What do you think of the category 'schema validators' or 'data schema validators'? Their documentation describes them as schema validators.

**Comment by Maximization** [comment]
I'd say let's go with "Object Schema Validators" 👍. Could you please update the PR to add the new category?

**Comment by maikofelix47** [comment]
@Maximization Done!

**Comment by Maximization** [comment]
https://nodejstoolbox.com/categories/object-schema-validators 🚀

**Pull request merged**
